# Site settings
title: Aquaboat
baseurl: "/aquaboat.ch"
url: "" # the base hostname & protocol for your site
email: "hello@aquaboat.ch"
phone:

# Build settings
markdown: kramdown
exclude: [node_modules]
