---
- title: Comparateur bateau
  content: Profitez de notre comparateur online pour trouver le bateau de vos rêves.
  image: forestryio/images/comparateur.jpg
  link: buy
- title: Les bonnes affaires
  content: Pour compléter notre gamme, nous vous proposons un large choix d'objet
    d'occasion, ainsi que des déstockages de bateaux d'usine ou  des promotions pré-saison.
  image: forestryio/images/bonne-affaire.jpg
  link: occasion
- title: Nos prestations
  content: |
    Pour vous assurer  confort et sécurité,  nous mettons à votre disposition  toute une gamme de prestations,  depuis l'hivernage  de votre bateau à  la rénovation de votre moteur ou de votre coque.
  image: forestryio/images/prestation-1.jpg
  link: shipyard
- title: Restez en contact avec nous
  content: |
    Avez-vous des questions?  Nous sommes à votre disposition du lundi au vendredi , le samedi sur rendez-vous, ou par notre formulaire de contact.
  image: forestryio/images/contact.jpg
  link: contact
