---
- title: Comparateur bateau
  content: Profitez de notre comparateur online pour trouver le bateau de vos rêves,
    selon vos critères de recherche.
  image: forestryio/images/198lx.jpg
- title: Contactez nous
  content: ''
  image: "/forestryio/images/20160816_174045.jpg"
- title: Nos prestations
  content: "Pour assurer votre confort et votre sécurité,  nous mettons à votre disposition
    \ toutes une gamme de prestations.\r\n"
  image: forestryio/images/prestation-1.jpg
- title: Occasion
  content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Atqui eorum nihil
    est eius generis, ut sit in fine atque extrerno bonorum. Teneo, inquit, finem
    illi videri nihil dolere. Tecum optime, deinde etiam cum mediocri amico. An eum
    discere ea mavis, quae cum plane perdidiceriti nihil sciat? Ratio quidem vestra
    sic cogit.
  image: "/forestryio/images/services.jpg"
