---
- title: Comparateur bateau
  content: Profitez de notre comparateur online pour trouver le bateau de vos rêves.
  image: forestryio/images/compar.jpg
  link: boat
- title: Les bonnes affaires
  content: |-
    &#149 Large choix d'objets d'occasion<br>
    &#149 Destockage de bateau d'usine<br>
    &#149 Promotion pré -saison<br>

    Soyez curieux! Venez découvrir nos bonnes affaires!
  image: forestryio/images/good-deal.jpg
  link: occasion
- title: Hivernage et stockage
  content: Avec 5'000 m2 de stockage sécurisé, sous bâche thermoforé, nous sommes
    en mesure d'assurer le gardiennage de votre bateau. Notre équipe vous propose
    aussi un service d'entretien sur mesure. Vous serez ainsi prêt pour vivre une
    nouvelle saison en toute sérénité!
  image: forestryio/images/presta.jpg
  link: shipyard
- title: Restez en contact avec nous
  content: 'Avez-vous des questions?  Nous sommes à votre disposition du lundi au
    vendredi , le samedi sur rendez-vous, ou par notre formulaire de contact.

'
  image: forestryio/images/contact-nous.jpg
  link: contact
