---
- title: Comparateur bateau
  content: Profitez de notre comparateur online pour trouver le bateau de vos rêves,
    selon vos critères de recherche.
  image: forestryio/images/198lx.jpg
- title: Nos prestations
  content: "Pour assurer votre confort et votre sécurité,  nous mettons à votre disposition
    \ toutes une gamme de prestations, de l'hivernage de votre bateau à la rénovation
    de votre moteur ou coque.\r\n"
  image: forestryio/images/prestation-1.jpg
- title: Les bonnes affaires
  content: Pour compléter notre gamme nous vous proposons une large choix d'objet
    d'occasion, ainsi que des déstockages bateau d'usines ou encore des promotions
    pré-saison.
  image: "/forestryio/images/services.jpg"
- title: Contactez nous
  content: ''
  image: "/forestryio/images/20160816_174045.jpg"
